POST http://localhost:3001/api/blogs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11a3VkYW5pZXJ1IiwiaWQiOiI2OWEyZDc0MTczOGViMDY0YzQzMmFhZDUiLCJpYXQiOjE3NzIzNDkwOTYsImV4cCI6MTc3MjM1MjY5Nn0.0lCUUuoxaOCxDo68cIFhZ5u0jbFrswgn__AGDh0C17E
Content-Type: application/json

# {
#     "title": "Understanding REST APIs",
#     "author": "John Doe",
#     "url": "https://example.com/rest-apis",
#     "likes": 10,
#     "userId" : "69a2d741738eb064c432aad5"
# }

{
    "title": "Building APIs with Express",
    "author": "Wes Bos",
    "url": "https://wesbos.com/express-api-guide"
}
